/**
 * PDF Report Generator for Local Audit Tool
 * Generates professional PDF audit reports
 */

const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

async function generateAuditReport(auditData, options = {}) {
  const {
    logoUrl = null,
    companyName = 'Website Audit Report',
    primaryColor = '#2563eb',
    includeCharts = true,
    includeRecommendations = true
  } = options;

  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 60, bottom: 60, left: 50, right: 50 },
        info: {
          Title: `SEO Audit Report - ${auditData.url}`,
          Author: companyName,
          Subject: 'Website SEO Analysis',
          Creator: 'Local Audit Tool v4.1'
        }
      });

      const chunks = [];
      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Helper functions
      const addPage = () => {
        doc.addPage({ size: 'A4', margins: { top: 60, bottom: 60, left: 50, right: 50 } });
      };

      const formatDate = (date) => {
        return new Date(date).toLocaleDateString('en-US', {
          year: 'numeric',
          month: 'long',
          day: 'numeric'
        });
      };

      const getGradeColor = (grade) => {
        const colors = {
          'A': '#16a34a',
          'B': '#84cc16',
          'C': '#eab308',
          'D': '#f97316',
          'F': '#dc2626'
        };
        return colors[grade] || '#6b7280';
      };

      const getRatingColor = (rating) => {
        const colors = {
          'good': '#16a34a',
          'needs-improvement': '#eab308',
          'poor': '#dc2626'
        };
        return colors[rating] || '#6b7280';
      };

      // ==================== PAGE 1: COVER ====================
      
      // Header line
      doc.rect(50, 50, doc.page.width - 100, 3)
         .fill(primaryColor);

      // Company name (white-label)
      doc.fontSize(24)
         .font('Helvetica-Bold')
         .fillColor('#1f2937')
         .text(companyName, 50, 80, { align: 'center' });

      // Title
      doc.fontSize(36)
         .font('Helvetica-Bold')
         .fillColor(primaryColor)
         .text('Website Audit Report', { align: 'center' });

      doc.moveDown(2);

      // URL
      doc.fontSize(14)
         .font('Helvetica')
         .fillColor('#4b5563')
         .text(auditData.url, { align: 'center' });

      doc.moveDown(0.5);

      // Date
      doc.fontSize(12)
         .fillColor('#6b7280')
         .text(`Generated: ${formatDate(auditData.timestamp || new Date())}`, { align: 'center' });

      // Score circle
      const scoreY = doc.y + 80;
      const scoreX = doc.page.width / 2;
      const scoreRadius = 70;

      // Outer circle
      doc.circle(scoreX, scoreY, scoreRadius)
         .lineWidth(8)
         .stroke(getGradeColor(auditData.grade));

      // Score text
      doc.fontSize(48)
         .font('Helvetica-Bold')
         .fillColor(getGradeColor(auditData.grade))
         .text(auditData.score.toString(), scoreX - 25, scoreY - 30, { width: 50, align: 'center' });

      // Grade
      doc.fontSize(24)
         .fillColor('#374151')
         .text(`Grade: ${auditData.grade}`, { align: 'center' });

      doc.moveDown(2);

      // Industry comparison
      if (auditData.comparison) {
        doc.fontSize(12)
           .fillColor('#6b7280')
           .text(`Industry: ${auditData.industryName || 'General'}`)
           .text(`vs Industry Average: ${auditData.comparison.industryAverage}/100`);
      }

      // Footer
      doc.fontSize(10)
         .fillColor('#9ca3af')
         .text('Generated by Local Audit Tool v4.1', 50, doc.page.height - 40, { 
           align: 'center', 
           width: doc.page.width - 100 
         });

      // ==================== PAGE 2: SUMMARY ====================
      addPage();

      // Header
      doc.rect(50, 50, doc.page.width - 100, 3)
         .fill(primaryColor);

      doc.fontSize(20)
         .font('Helvetica-Bold')
         .fillColor('#1f2937')
         .text('Executive Summary', { align: 'center' });

      doc.moveDown(1.5);

      // Summary box
      doc.rect(70, 120, doc.page.width - 140, 80)
         .fill('#f8fafc');

      doc.fontSize(12)
         .font('Helvetica')
         .fillColor('#374151');

      const summaryY = 140;
      doc.text('This comprehensive audit analyzes your website across multiple dimensions including technical SEO, content quality, performance, and user experience. The report identifies key areas for improvement and provides actionable recommendations.', 90, summaryY, { 
        width: doc.page.width - 180,
        lineGap: 5
      });

      // Key metrics
      doc.moveDown(2);

      // Metrics grid
      const metrics = [
        { label: 'Overall Score', value: `${auditData.score}/100`, color: primaryColor },
        { label: 'Pages Analyzed', value: auditData.pages?.totalPages?.toString() || '1', color: '#059669' },
        { label: 'Keywords Found', value: (auditData.keywords?.primary?.length || 0).toString(), color: '#7c3aed' },
        { label: 'Tech Detected', value: getTechCount(auditData.techStack).toString(), color: '#db2777' }
      ];

      let metricX = 70;
      const metricWidth = (doc.page.width - 140) / 2;

      metrics.forEach((metric, i) => {
        const row = Math.floor(i / 2);
        const col = i % 2;
        const x = 70 + (col * (metricWidth + 20));
        const y = 240 + (row * 70);

        doc.rect(x, y, metricWidth, 55)
           .fill('#f8fafc');

        doc.fontSize(10)
           .fillColor('#6b7280')
           .text(metric.label, x + 15, y + 10);

        doc.fontSize(22)
           .font('Helvetica-Bold')
           .fillColor(metric.color)
           .text(metric.value, x + 15, y + 25);
      });

      // Tech stack detected
      if (auditData.techStack) {
        doc.fontSize(14)
           .font('Helvetica-Bold')
           .fillColor('#1f2937')
           .text('Technology Detected', 50, 450);

        const techGroups = [
          { label: 'CMS', data: auditData.techStack.cms },
          { label: 'Frameworks', data: auditData.techStack.frameworks },
          { label: 'Analytics', data: auditData.techStack.analytics },
          { label: 'Hosting', data: auditData.techStack.hosting }
        ];

        let techY = 475;
        techGroups.forEach(group => {
          if (group.data && group.data.length > 0) {
            doc.fontSize(10)
               .font('Helvetica-Bold')
               .fillColor(primaryColor)
               .text(`${group.label}:`, 70, techY);
            
            doc.fontSize(10)
               .font('Helvetica')
               .fillColor('#374151')
               .text(group.data.join(', '), 150, techY);
            
            techY += 18;
          }
        });
      }

      // ==================== PAGE 3-5: CHECKS BY CATEGORY ====================
      if (auditData.checks && auditData.checks.length > 0) {
        addPage();
        
        doc.rect(50, 50, doc.page.width - 100, 3)
           .fill(primaryColor);

        doc.fontSize(20)
           .font('Helvetica-Bold')
           .fillColor('#1f2937')
           .text('Detailed Analysis', { align: 'center' });

        doc.moveDown(1);

        // Group checks by category
        const categories = {};
        auditData.checks.forEach(check => {
          if (!categories[check.category]) {
            categories[check.category] = [];
          }
          categories[check.category].push(check);
        });

        const categoryNames = {
          'security': 'Security',
          'performance': 'Performance',
          'seo': 'SEO',
          'technical': 'Technical',
          'social': 'Social & Sharing',
          'ux': 'User Experience',
          'links': 'Links',
          'branding': 'Branding'
        };

        for (const [cat, checks] of Object.entries(categories)) {
          if (doc.y > doc.page.height - 150) {
            addPage();
          }

          doc.fontSize(14)
             .font('Helvetica-Bold')
             .fillColor(primaryColor)
             .text(categoryNames[cat] || cat.toUpperCase());

          doc.moveDown(0.5);

          checks.forEach(check => {
            const statusIcon = check.passed ? '✓' : '✗';
            const statusColor = check.passed ? '#16a34a' : '#dc2626';
            
            doc.fontSize(10)
               .font('Helvetica')
               .fillColor(statusColor)
               .text(`${statusIcon} ${check.issue}`, { continued: false });

            doc.fontSize(9)
               .fillColor('#6b7280')
               .text(`   ${check.message}`, { align: 'left' });

            doc.moveDown(0.3);
          });

          doc.moveDown(0.5);
        }
      }

      // ==================== PAGE 6+: RECOMMENDATIONS ====================
      if (includeRecommendations && auditData.recommendations) {
        addPage();

        doc.rect(50, 50, doc.page.width - 100, 3)
           .fill(primaryColor);

        doc.fontSize(20)
           .font('Helvetica-Bold')
           .fillColor('#1f2937')
           .text('Recommendations', { align: 'center' });

        doc.moveDown(1);

        const recommendations = auditData.recommendations.filter(r => !r.passed);

        if (recommendations.length === 0) {
          doc.fontSize(12)
             .font('Helvetica')
             .fillColor('#16a34a')
             .text('Great job! All checks passed.', { align: 'center' });
        } else {
          recommendations.forEach((rec, i) => {
            if (doc.y > doc.page.height - 100) {
              addPage();
            }

            doc.fontSize(12)
               .font('Helvetica-Bold')
               .fillColor('#dc2626')
               .text(`${i + 1}. ${rec.issue}`);

            doc.fontSize(10)
               .font('Helvetica')
               .fillColor('#374151')
               .text(`   ${rec.message}`, { indent: 10 });

            doc.moveDown(0.5);
          });
        }
      }

      // ==================== FINAL PAGE: FOOTER ====================
      addPage();

      doc.rect(50, 50, doc.page.width - 100, 3)
         .fill(primaryColor);

      doc.fontSize(16)
         .font('Helvetica-Bold')
         .fillColor('#1f2937')
         .text('About This Report', { align: 'center' });

      doc.moveDown(1);

      doc.fontSize(11)
         .font('Helvetica')
         .fillColor('#374151')
         .text('This audit report was generated by Local Audit Tool v4.1, a comprehensive website analysis platform that evaluates websites across 25+ metrics including SEO optimization, technical performance, content quality, and user experience.')
         .moveDown(0.5)
         .text(`Report generated: ${formatDate(new Date())}`)
         .text(`Website analyzed: ${auditData.url}`)
         .moveDown(0.5)
         .text(`Score: ${auditData.score}/100 (Grade: ${auditData.grade})`);

      doc.moveDown(1.5);

      doc.fontSize(14)
         .font('Helvetica-Bold')
         .fillColor(primaryColor)
         .text('Ready to improve your website?', { align: 'center' });

      doc.fontSize(11)
         .font('Helvetica')
         .fillColor('#6b7280')
         .text('Contact us for professional SEO services and website optimization.', { align: 'center' });

      // Final footer
      doc.fontSize(9)
         .fillColor('#9ca3af')
         .text(`${companyName} | Local Audit Tool v4.1`, 50, doc.page.height - 40, { 
           align: 'center', 
           width: doc.page.width - 100 
         });

      // Finalize
      doc.end();

    } catch (error) {
      reject(error);
    }
  });
}

// Helper function to count technologies
function getTechCount(techStack) {
  if (!techStack) return 0;
  let count = 0;
  Object.values(techStack).forEach(arr => {
    if (Array.isArray(arr)) count += arr.length;
  });
  return count;
}

module.exports = { generateAuditReport };
/**
 * PDF Report Generation API
 * Generates professional audit reports in PDF format
 */

const { generateAuditReport } = require('./pdf-report');

module.exports = async (req, res) => {
  try {
    const { 
      url, 
      // White-label options
      companyName = 'Website Audit Report',
      logoUrl = null,
      primaryColor = '#2563eb',
      // Audit data (passed directly or reference)
      auditData,
      // Report options
      includeCharts = true,
      includeRecommendations = true
    } = req.body;

    // Validate input
    if (!auditData) {
      return res.status(400).json({
        error: 'auditData is required',
        example: {
          url: 'https://example.com',
          auditData: { /* full audit result object */ },
          companyName: 'My SEO Agency',
          primaryColor: '#2563eb'
        }
      });
    }

    // Validate audit data has required fields
    const requiredFields = ['url', 'score', 'grade'];
    for (const field of requiredFields) {
      if (!auditData[field]) {
        return res.status(400).json({
          error: `Missing required field: ${field}`,
          auditData: auditData
        });
      }
    }

    console.log(`[PDF Report] Generating report for: ${auditData.url}`);

    // Generate PDF
    const pdfBuffer = await generateAuditReport(auditData, {
      companyName,
      logoUrl,
      primaryColor,
      includeCharts,
      includeRecommendations
    });

    console.log(`[PDF Report] Generated ${pdfBuffer.length} bytes`);

    // Send response
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="audit-report-${new URL(auditData.url).hostname}-${Date.now()}.pdf"`);
    res.send(pdfBuffer);

  } catch (error) {
    console.error('[PDF Report] Error:', error.message);
    res.status(500).json({
      error: 'Failed to generate PDF report',
      message: error.message,
      suggestion: 'Check that all required audit data is present'
    });
  }
};
